### ISSUE TITLE
Potential timing issue

### ISSUE THREAD

**Issue by etki** [EmbarkStudios/tiny-bench#10]
**Describe the bug**
Hey - this may be correct as long as i read rust code correctly, i'm coding in other languages. Please excuse me if the text below is not correct.

In https://github.com/EmbarkStudios/tiny-bench/blob/main/tiny-bench/src/benching.rs#L228-L230 i see the following:

```rust
let start = Instant::now();
black_box((closure)(input));
elapsed += Instant::now().duration_since(start);
```

which, to me, seems to be timing every invocation of the benched code. The potential issue here is that the timer call contains overhead by itself (significant compared to really small operations): the captured value would contain the timing of Instant::now after it acquired the timestamp, then the benchmark itself, then the timing of Instant::now before it acquires the timestamp, skewing the results; as for now, i have just a single silly example obtained on a single machine, but there it took 55-60ns. If, for example, two benchmarks take 5 and 10ns respectively, and the timer call takes 55ns, then the 100% difference will convert into only into ~8.33%. So i think it is worth to run a number of internal wrapping iterations, with every wrapping iteration running looping for a predefined / configuration number (sadly i can't provide a decent one), and collect the timing at the boundaries of such a wrapping iteration. It would also help to provide some statistics on the variance / standard deviation - while by itself it usually doesn't apply to tight code samples, high values would tell end user that there is something wrong with the setup (e.g. chrome running in background).

**Comment by MarcusGrass** [comment]
Hi etki, 

You're right in that timings latency sneaks in, although it only applies to benches with a setup function for a few annoying reasons.

So, it only applies to setups, where you have some bench function that takes some input provided by a closure.
Since the value of that closure isn't necessarily clone or copy, that function has to be run before each test. Since we don't want to include the latency of that setup function, each test has to be timed individually after generating the setup data*. Even if it was copy or clone, we wouldn't want to include the copying/cloning-latency in each test's latency either, that's the same issue that including half of the timer bring, just a bit different.

This is *essentially* a stripping down of criterion, you can find the section here https://github.com/bheisler/criterion.rs/blob/master/src/bencher.rs#L245. 
*
But, something that criterion does differently is this: https://github.com/bheisler/criterion.rs/blob/master/src/bencher.rs#L262 putting all the samples in a vector. This has the potential to explode ram but it improves measurement error and puts it at about the same as without a setup function.

On exploding ram: The most amount of iterations that you can get are 5 billion, at that many iterations, the maximum sample will have `99 010 000` items. At one byte per input value, that's 99M, which could be acceptable, since 5B is the top-end, but it bears some thought.

You can test this out pretty easily.

No changes: 
```rust
fn bench_test_five() {
    tiny_bench::bench_with_setup_labeled(
        "test five, setup noop",
        || 5,
        |_i| {},
    );
}
/* Outputs
test five, setup noop warming up for 3.00s
test five, setup noop mean warm up execution time 0.00ns running 5.0B iterations
test five, setup noop [5.0B iterations in 78.36s with 100.0 samples]:
        elapsed [min mean max]: [15.00ns 15.67ns 16.44ns] (sample data: med = 15.49ns, var = 0.32ns², stddev = 0.56ns)
        change  [min mean max]: [0.0763% 2.0477% -0.4874%] (p = 0.00)
*/
```
With pre-generating inputs and putting them in ram:
No changes: 
```rust
fn bench_test_five() {
    tiny_bench::bench_with_setup_labeled(
        "test five, setup noop",
        || 5,
        |_i| {},
    );
}
/* Outputs
test five, setup noop warming up for 3.00s
test five, setup noop mean warm up execution time 0.00ns running 5.0B iterations
test five, setup noop [5.0B iterations in 1.05s with 100.0 samples]:
        elapsed [min mean max]: [0.20ns 0.21ns 0.29ns] (sample data: med = 0.21ns, var = 0.00ns², stddev = 0.01ns)
        change  [min mean max]: [9.1625% 9.0357% 23.3268%] (p = 0.00)
*/
```
That's a 0.21ns measurement error since we're measuring a no-op, that's the same measurement error as a bench without a setup. I think that's an improvement.

Worst case scenario here is that a user will need to provide a `max_iterations` to keep memory from exploding on extremely fast benches with big setup inputs. I think criterion suffers the same issue if I haven't misunderstood the code, and this project aims to be pretty much the same but lighter so it's acceptable to make the same tradeoffs as criterion does.

Thanks for the report, I'll create an update.
