### ISSUE TITLE
Feature request: additional statistics

### ISSUE THREAD

**Issue by lqd** [EmbarkStudios/tiny-bench#4]
While trying to visualize some benchmark data I gathered with tiny-bench (👍) I wanted to add a confidence range, but tiny-bench didn't seem to provide more data than min/max/mean (I could be wrong).

Discussing this with the great @bnjbvr, we thought we'd open an issue to track whether additional statistics could be computed:
- the median
- variance and standard deviation (although maybe that can be confusing for some distributions)
- percentiles / quartiles, with an eye towards eliminating outliers like criterion

Is this something tiny-bench could do in the future maybe ?
Thanks in advance

**Comment by MarcusGrass** [comment]
I'm by no means an expert in benchmarking or sampling methodology, when I was porting the parts I would like to see from criterion standard deviation was something I was looking into but I think that when doing a t-test like tiny-bench does you can't easily calculate standard deviation.
Variance is already calculated, just not displayed, median is easily calculated, and I actually included percentiles in the first iteration but decided to scrap it because I couldn't figure out an ergonomic way for the user to provide what percentiles they wanted to run, and I didn't want to make that decision. In the end I left it out pending someone wanting it, now that someone does, I'll try to figure out a way to add it!

**Comment by bnjbvr** [comment]
Thanks for explaining! And thanks for bunch for implementing this :heart: 

I think if we _really really_ wanted to get the variance over the individual values (and not samples), there has to be an inductive formula to compute it. There's such a formula for the mean too. Given variance V[N] for the distribution of N samples, given E the mean, then the new variance when adding the (N+1)th value would be `(N * V[N] + (new value - E)) / (N + 1)`, or something like that. I don't know if it's practically feasible, as in fast enough, but that would avoid the hard toll on memory.
